
[postgres]
host = "tai.db.elephantsql.com"
port = 5432
dbname = "bjvsinga"
user = "bjvsinga"
password = "Eifswy6LwMR_XxhhLOuADg3oU-mWoOc2"

 host="",
    
    password="Eifswy6LwMR_XxhhLOuADg3oU-mWoOc2",
